### ISSUE TITLE
Technical Question 

### ISSUE THREAD

**Issue by mgiaco** [swift-nav/piksi_buildroot#1133]
Hello, 
I would like to use a similar approach as you use for the multi. I would like to use one core with linux and one with some custom firmware running Safertos or plain C. This is only the linux for Core1 and the firmware for the other core is closed source? Or is the repository also here on github?
I am wondering how the communication between these 2 Cores works.

many thanks
cheers
mathias

**Comment by silverjam** [comment]
Hi @mgiaco -- the other core is indeed closed source, but any RTOS should be able to run in this configuration.  We use remoteproc on Linux to load our RTOS onto one of the processors.  We're using rpmsg to communicate between the two processors.  We've allocated most peripherals to Linux, but some are specifically allocated to the RTOS.  For reference, the old Piksi v2 hardware (current hardware is the Piksi Multi) used ChibiOS as it's firmware: https://github.com/swift-nav/piksi_firmware (this is still open source).

**Comment by silverjam** [comment]
If you have other questions, please give support@swiftnav.com a shout 😃
