### ISSUE TITLE
Cannot Build Due to AWS Credentials

### ISSUE THREAD

**Issue by jaylthegreat** [swift-nav/piksi_buildroot#1340]
At this point I'm unsure if this repo is supposed to be mostly for in house development or not. 

For a project I'm working on, I need to make some slight modifications to the firmware of my piksi swiftnav board. I hoped that with this repo I could make these additions easily; however, I've run into a few issues.

It would seem that I need AWS credentials to download the firmware and FPGA binaries. I'm on branch v2.3.0-release (as the readme states that only tagged release branches would have these publicly available); however, when I run ```make image```, a pre-flight  check is failed on the script verify-aws-access. 

Additionally, in the readme it references a ```fetch-firmware.sh``` which is not present in this branch.

Sorry if this isn't really a bug, but at the very least it might be considered a feature request for better documentation.

Thanks for any help you can give!

**Comment by benjaminaltieri** [comment]
Hi @jaylthegreat - yes the documentation needs to be updated. To build without credentials, you must build the SDK variant of the firmware:
```
export VARIANT=sdk
make image
```
