### ISSUE TITLE
Possible runaway logs

### ISSUE THREAD

**Issue by jacobmcnamee** [swift-nav/piksi_buildroot#150]
It may be possible for logs to eat up all the space on the filesystem (RAM). We should verify that they are limited somehow.

**Comment by mfine** [comment]
:+1: this happened to me.

**Comment by jacobmcnamee** [comment]
I haven't tested this yet, but it looks like busybox syslogd should be limiting each log to 200kB with only one level of rotation (e.g. only `/var/log/messages` and `/var/log/messages.0`). If that's true, then we just need to finish migrating to `syslog()` / `piksi_log()`.

**Comment by jacobmcnamee** [comment]
Tested to confirm my previous comment.
