### ISSUE TITLE
Piksi INS

### ISSUE THREAD

**Issue by kylerlaird** [swift-nav/piksi_buildroot#880]
What is Piksi INS and where can I get it?  I don't see it in carnegieroboticsllc's github repositories.

**Comment by cbeighley** [comment]
Hi Kyle, Piksi INS is our loosely coupled GNSS/INS solution we're working on, which is a joint development with Carnegie Robotics. It is proprietary, so unfortunately you will not be able to acquire the source or build a Piksi Multi SDK image that contains the INS software. You can contact sales@swiftnav.com if you're interested in purchasing it.
